import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, "..");

const COLOR_RE = /^(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)|color-mix\((?:[^()]|\([^()]*\))*\)|hsla?\([^)]*\))$/;
const MODES = ["dark", "light"];

const HEADER =
  "/* GENERATED by @shogun-ai/tokens (scripts/build.mjs from src/tokens.json). Do not edit by hand. */\n";

function themedBlock(themed, mode) {
  return Object.entries(themed)
    .map(([name, byMode]) => `  --${name}: ${byMode[mode]};`)
    .join("\n");
}

function staticBlock(statics) {
  return Object.entries(statics)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
}

export function generateCss(tokens) {
  const statics = tokens.static ?? {};
  const themed = tokens.themed ?? {};
  return (
    HEADER +
    `:root {\n${staticBlock(statics)}\n${themedBlock(themed, "dark")}\n}\n` +
    `:root[data-appearance="dark"] {\n${themedBlock(themed, "dark")}\n}\n` +
    `:root[data-appearance="light"] {\n${themedBlock(themed, "light")}\n}\n` +
    `@media (prefers-color-scheme: light) {\n  :root[data-appearance="auto"] {\n${themedBlock(themed, "light")
      .split("\n")
      .map((l) => "  " + l)
      .join("\n")}\n  }\n}\n`
  );
}

export function generateTs(tokens) {
  const json = JSON.stringify(
    { static: tokens.static ?? {}, themed: tokens.themed ?? {} },
    null,
    2,
  );
  return (
    "// GENERATED by @shogun-ai/tokens (scripts/build.mjs). Do not edit by hand.\n" +
    `export const tokens = ${json} as const;\n` +
    "export type TokenName = keyof (typeof tokens)[\"themed\"] | keyof (typeof tokens)[\"static\"];\n"
  );
}

export function main() {
  const tokens = JSON.parse(readFileSync(resolve(PKG, "src/tokens.json"), "utf8"));
  const errors = validate(tokens);
  if (errors.length) {
    console.error("Token validation failed:\n" + errors.map((e) => "  - " + e).join("\n"));
    process.exit(1);
  }
  mkdirSync(resolve(PKG, "dist"), { recursive: true });
  writeFileSync(resolve(PKG, "dist/tokens.css"), generateCss(tokens));
  writeFileSync(resolve(PKG, "dist/tokens.ts"), generateTs(tokens));
  console.log("Wrote dist/tokens.css and dist/tokens.ts");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

/** @returns {string[]} list of human-readable errors (empty = valid) */
export function validate(tokens) {
  const errors = [];
  const themed = tokens.themed ?? {};
  for (const [name, byMode] of Object.entries(themed)) {
    for (const mode of MODES) {
      const v = byMode?.[mode];
      if (v == null) {
        errors.push(`themed token "${name}" is missing mode "${mode}"`);
        continue;
      }
      if (!COLOR_RE.test(String(v).trim())) {
        errors.push(`themed token "${name}" (${mode}) has an invalid color value: ${v}`);
      }
    }
  }
  return errors;
}
