//! Morning Brief assembly (WP3.5, §6.8 / FR-MB-01..06). The prose ("What happened", the polished
//! wording) is generated by the Batch API in the Dream Cycle's final job — but *which* items go in
//! *which* section, *in what order*, *capped where*, and *how confidence is marked* is pure,
//! deterministic assembly, tested here without a network.
//!
//! Rules encoded:
//! - Sections and their sources (FR-MB-01): Today (calendar, time-ordered) · Commitments due ·
//!   Open loops (top-5 by staleness) · What happened (≤5 lines) · Suggested actions (≤3, each
//!   L2/L3-tagged via [`ActionCandidate`]).
//! - Confidence (FR-MB-05, via [`crate::confidence`]): Low (<0.5) state is **excluded** — never
//!   shown as a morning fact; Medium (0.5..<0.8) is flagged `possibly` for the UI to distinguish;
//!   High passes through. Provenance travels with every item.
//! - Degraded brief (FR-MB-04): when generation failed, show local-only data (calendar + overdue
//!   commitments), no LLM prose, no suggestions — never an empty/error screen at 8am.

use crate::assemble::ActionCandidate;
use crate::confidence::{band, Band};

/// Max open loops shown (FR-MB-01: top-5 by staleness).
pub const OPEN_LOOPS_MAX: usize = 5;
/// Max suggested actions (FR-MB-01: ≤3).
pub const SUGGESTED_ACTIONS_MAX: usize = 3;
/// Max "What happened" lines (FR-MB-01: 3–5 lines; assembly caps the upper bound).
pub const WHAT_HAPPENED_MAX: usize = 5;

/// A calendar entry for Today (FR-MB-01). Meeting Prep is offered for every entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CalendarLine {
    pub start_ms: i64,
    pub title: String,
    /// FR-MB-06: changed after the brief was generated (shown with an "Updated" mark).
    pub updated: bool,
}

/// A commitment for the "Commitments due" section (today-due or overdue).
#[derive(Debug, Clone)]
pub struct CommitmentDue {
    pub description: String,
    pub due_at_ms: Option<i64>,
    pub overdue: bool,
    pub confidence: f64,
    pub provenance_event_id: i64,
}

/// An open loop for the "Open loops" section.
#[derive(Debug, Clone)]
pub struct OpenLoopItem {
    pub description: String,
    pub staleness_days: u32,
    pub confidence: f64,
    pub provenance_event_id: i64,
}

/// One rendered brief line, with provenance and the `possibly` (medium-confidence) marker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BriefItem {
    pub text: String,
    pub provenance_event_id: i64,
    /// FR-MB-05: medium-confidence (0.5..<0.8) items are flagged so the UI can mark them "possibly".
    pub possibly: bool,
}

/// The assembled Morning Brief.
#[derive(Debug, Clone)]
pub struct MorningBrief {
    pub today: Vec<CalendarLine>,
    pub commitments_due: Vec<BriefItem>,
    pub open_loops: Vec<BriefItem>,
    /// Yesterday's summary (3–5 lines). Empty in a degraded brief.
    pub what_happened: Vec<String>,
    /// ≤3 suggested actions, each already L2/L3-tagged. Empty in a degraded brief.
    pub suggested_actions: Vec<ActionCandidate>,
    /// FR-MB-04: true when this is the local-only fallback (no LLM prose).
    pub degraded: bool,
}

/// Render one confidence-bearing item, or `None` when it is Low (excluded, FR-MB-05/FR-ST-20).
fn to_item(text: &str, confidence: f64, provenance_event_id: i64) -> Option<BriefItem> {
    match band(confidence) {
        Band::Low => None,
        b => Some(BriefItem {
            text: text.to_string(),
            provenance_event_id,
            possibly: b == Band::Medium,
        }),
    }
}

/// Order today's calendar by start time (FR-MB-01: time-ordered).
fn ordered_today(mut calendar: Vec<CalendarLine>) -> Vec<CalendarLine> {
    calendar.sort_by_key(|c| c.start_ms);
    calendar
}

/// Order commitments: overdue first, then by due time ascending (soonest first); undated last.
fn ordered_commitments(commitments: &[CommitmentDue]) -> Vec<BriefItem> {
    let mut kept: Vec<(&CommitmentDue, BriefItem)> = commitments
        .iter()
        .filter_map(|c| to_item(&c.description, c.confidence, c.provenance_event_id).map(|i| (c, i)))
        .collect();
    kept.sort_by(|(a, _), (b, _)| {
        // overdue (true) sorts before not-overdue
        b.overdue
            .cmp(&a.overdue)
            .then_with(|| a.due_at_ms.unwrap_or(i64::MAX).cmp(&b.due_at_ms.unwrap_or(i64::MAX)))
    });
    kept.into_iter().map(|(_, i)| i).collect()
}

/// Top open loops by staleness (desc), capped at [`OPEN_LOOPS_MAX`]; Low-confidence excluded.
fn top_open_loops(open_loops: &[OpenLoopItem]) -> Vec<BriefItem> {
    let mut kept: Vec<(&OpenLoopItem, BriefItem)> = open_loops
        .iter()
        .filter_map(|o| to_item(&o.description, o.confidence, o.provenance_event_id).map(|i| (o, i)))
        .collect();
    kept.sort_by_key(|(b, _)| std::cmp::Reverse(b.staleness_days));
    kept.into_iter().take(OPEN_LOOPS_MAX).map(|(_, i)| i).collect()
}

/// Assemble the full Morning Brief (FR-MB-01). Suggested actions are taken pre-ranked from
/// Fusion / Follow-up Sentinel and capped at [`SUGGESTED_ACTIONS_MAX`]; "What happened" is capped
/// at [`WHAT_HAPPENED_MAX`] lines.
pub fn assemble_brief(
    calendar: Vec<CalendarLine>,
    commitments: &[CommitmentDue],
    open_loops: &[OpenLoopItem],
    what_happened: Vec<String>,
    suggested: Vec<ActionCandidate>,
) -> MorningBrief {
    let mut what = what_happened;
    what.truncate(WHAT_HAPPENED_MAX);
    let mut actions = suggested;
    actions.truncate(SUGGESTED_ACTIONS_MAX);
    MorningBrief {
        today: ordered_today(calendar),
        commitments_due: ordered_commitments(commitments),
        open_loops: top_open_loops(open_loops),
        what_happened: what,
        suggested_actions: actions,
        degraded: false,
    }
}

/// Assemble the degraded, local-only brief (FR-MB-04): calendar + overdue commitments only, no LLM
/// prose, no suggestions. Shown when Dream Cycle / Batch generation failed so the morning is never
/// an empty or error screen.
pub fn assemble_degraded(calendar: Vec<CalendarLine>, commitments: &[CommitmentDue]) -> MorningBrief {
    // Only overdue commitments in the fallback — the local, unambiguous ones.
    let overdue: Vec<CommitmentDue> = commitments.iter().filter(|c| c.overdue).cloned().collect();
    MorningBrief {
        today: ordered_today(calendar),
        commitments_due: ordered_commitments(&overdue),
        open_loops: Vec::new(),
        what_happened: Vec::new(),
        suggested_actions: Vec::new(),
        degraded: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn commitment(desc: &str, due: Option<i64>, overdue: bool, conf: f64, ev: i64) -> CommitmentDue {
        CommitmentDue { description: desc.into(), due_at_ms: due, overdue, confidence: conf, provenance_event_id: ev }
    }
    fn loop_item(desc: &str, staleness: u32, conf: f64, ev: i64) -> OpenLoopItem {
        OpenLoopItem { description: desc.into(), staleness_days: staleness, confidence: conf, provenance_event_id: ev }
    }
    fn cal(start: i64, title: &str) -> CalendarLine {
        CalendarLine { start_ms: start, title: title.into(), updated: false }
    }

    #[test]
    fn today_is_time_ordered() {
        let brief = assemble_brief(
            vec![cal(300, "late"), cal(100, "early"), cal(200, "mid")],
            &[],
            &[],
            vec![],
            vec![],
        );
        let titles: Vec<&str> = brief.today.iter().map(|c| c.title.as_str()).collect();
        assert_eq!(titles, vec!["early", "mid", "late"]);
    }

    #[test]
    fn low_confidence_commitments_and_loops_are_excluded() {
        let brief = assemble_brief(
            vec![],
            &[commitment("shaky", Some(10), false, 0.3, 1), commitment("solid", Some(10), false, 0.9, 2)],
            &[loop_item("shaky loop", 9, 0.4, 3), loop_item("real loop", 9, 0.85, 4)],
            vec![],
            vec![],
        );
        assert_eq!(brief.commitments_due.len(), 1);
        assert_eq!(brief.commitments_due[0].text, "solid");
        assert_eq!(brief.open_loops.len(), 1);
        assert_eq!(brief.open_loops[0].text, "real loop");
    }

    #[test]
    fn medium_confidence_items_are_flagged_possibly() {
        let brief = assemble_brief(
            vec![],
            &[commitment("maybe due", Some(10), false, 0.6, 1), commitment("certain", Some(10), false, 0.95, 2)],
            &[],
            vec![],
            vec![],
        );
        let maybe = brief.commitments_due.iter().find(|i| i.text == "maybe due").unwrap();
        let certain = brief.commitments_due.iter().find(|i| i.text == "certain").unwrap();
        assert!(maybe.possibly, "0.6 confidence must be flagged possibly");
        assert!(!certain.possibly, "0.95 confidence must not be flagged");
    }

    #[test]
    fn commitments_put_overdue_first_then_soonest() {
        let brief = assemble_brief(
            vec![],
            &[
                commitment("due later", Some(500), false, 0.9, 1),
                commitment("overdue", Some(100), true, 0.9, 2),
                commitment("due soon", Some(200), false, 0.9, 3),
            ],
            &[],
            vec![],
            vec![],
        );
        let order: Vec<&str> = brief.commitments_due.iter().map(|i| i.text.as_str()).collect();
        assert_eq!(order, vec!["overdue", "due soon", "due later"]);
    }

    #[test]
    fn open_loops_are_top_five_by_staleness() {
        let loops: Vec<OpenLoopItem> =
            (0..8).map(|i| loop_item(&format!("loop{i}"), i as u32, 0.9, i)).collect();
        let brief = assemble_brief(vec![], &[], &loops, vec![], vec![]);
        assert_eq!(brief.open_loops.len(), OPEN_LOOPS_MAX);
        // stalest first: loop7 (staleness 7) … loop3
        assert_eq!(brief.open_loops[0].text, "loop7");
        assert_eq!(brief.open_loops[4].text, "loop3");
    }

    #[test]
    fn what_happened_and_suggestions_are_capped() {
        let lines: Vec<String> = (0..9).map(|i| format!("line{i}")).collect();
        // build > 3 dummy actions via a simple local action
        use shogun_agents::permission::{Action, LocalAction};
        let mk = |q: &str| ActionCandidate {
            action: Action::Local(LocalAction::LocalSearch { query: q.into() }),
            level: Action::Local(LocalAction::LocalSearch { query: q.into() }).required_level(),
            rationale: q.into(),
        };
        let actions = vec![mk("a"), mk("b"), mk("c"), mk("d"), mk("e")];
        let brief = assemble_brief(vec![], &[], &[], lines, actions);
        assert_eq!(brief.what_happened.len(), WHAT_HAPPENED_MAX);
        assert_eq!(brief.suggested_actions.len(), SUGGESTED_ACTIONS_MAX);
    }

    #[test]
    fn degraded_brief_is_local_only_no_prose_or_suggestions() {
        let brief = assemble_degraded(
            vec![cal(100, "standup")],
            &[
                commitment("overdue thing", Some(50), true, 0.9, 1),
                commitment("not overdue", Some(999), false, 0.9, 2),
            ],
        );
        assert!(brief.degraded);
        assert_eq!(brief.today.len(), 1);
        // only the overdue commitment survives the fallback
        assert_eq!(brief.commitments_due.len(), 1);
        assert_eq!(brief.commitments_due[0].text, "overdue thing");
        assert!(brief.what_happened.is_empty());
        assert!(brief.suggested_actions.is_empty());
        assert!(brief.open_loops.is_empty());
    }

    #[test]
    fn provenance_travels_with_every_item() {
        let brief = assemble_brief(
            vec![],
            &[commitment("c", Some(1), false, 0.9, 42)],
            &[loop_item("l", 3, 0.9, 43)],
            vec![],
            vec![],
        );
        assert_eq!(brief.commitments_due[0].provenance_event_id, 42);
        assert_eq!(brief.open_loops[0].provenance_event_id, 43);
    }
}
